//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDeptFeesTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeLogs
    {
        public int Year { get; set; }
        public string VulkanID { get; set; }
        public int PaymentStatusID { get; set; }
        public Nullable<decimal> FeePayed { get; set; }
        public Nullable<decimal> FeeToPay { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
