//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireDeptFeesTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.FeeLogs = new HashSet<FeeLogs>();
        }
    
        public string VulkanID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public bool Gender { get; set; }
        public bool MustPay { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<FeeLogs> FeeLogs { get; set; }
    }
}
